return {
	{ "scottmckendry/cyberdream.nvim", opts = { transparent = true } },
	"mellow-theme/mellow.nvim",
	{ "folke/tokyonight.nvim", opts = { transparent = true } },
	"rebelot/kanagawa.nvim",
	"Shatur/neovim-ayu",
	"Mofiqul/dracula.nvim",
	"ellisonleao/gruvbox.nvim",
	"neanias/everforest-nvim",
	"EdenEast/nightfox.nvim",
	{ "catppuccin/nvim", name = "catppuccin" },
	{ "ribru17/bamboo.nvim", opts = { transparent = false } },
	"ramojus/mellifluous.nvim",
	"p00f/alabaster.nvim",
	{ "rose-pine/neovim", name = "rose-pine" },
	"maxmx03/solarized.nvim",
	{
		"catppuccin/nvim",
		name = "sakura",
		priority = 1000,
		config = function()
			require("catppuccin").setup({
				flavour = "mocha",
				color_overrides = {
					mocha = {
						base = "#0d0509",
						mantle = "#0d0509",
						crust = "#0d0509",
						text = "#f0eaed",
						subtext0 = "#D1B399",
						subtext1 = "#E3C5AB",
						surface0 = "#1a0f15",
						surface1 = "#2a1f25",
						surface2 = "#33333c",
						overlay0 = "#4a3c45",
						overlay1 = "#5a4c55",
						overlay2 = "#6a5c65",
						red = "#E85F6F",
						maroon = "#FF7A8A",
						peach = "#D4A882",
						yellow = "#E6BA94",
						green = "#F29B9A",
						teal = "#E8C099",
						sky = "#D9A56C",
						sapphire = "#EBB97E",
						blue = "#D9A56C",
						lavender = "#E3C5AB",
						pink = "#FF7A8A",
						rosewater = "#f0eaed",
						flamingo = "#FFB5B4",
					},
				},
			})
		end,
	},
}
