return {
	"mellow-theme/mellow.nvim",
	{ "folke/tokyonight.nvim", opts = { transparent = true } },
	-- "rebelot/kanagawa.nvim",
	-- "Shatur/neovim-ayu",
	-- "Mofiqul/dracula.nvim",
	-- "binhtran432k/dracula.nvim",
	-- "ellisonleao/gruvbox.nvim",
	-- "marko-cerovac/material.nvim",
	-- "neanias/everforest-nvim",
	-- "tomasiser/vim-code-dark",
	-- "EdenEast/nightfox.nvim",
	-- "sainnhe/sonokai",
	-- "catppuccin/nvim",
	-- "navarasu/onedark.nvim",
	{ "ribru17/bamboo.nvim", opts = { transparent = false } },
	"datsfilipe/vesper.nvim",
	"ramojus/mellifluous.nvim",
	{ "scottmckendry/cyberdream.nvim", opts = { transparent = true } },
	"p00f/alabaster.nvim",
	"timmyha/henna.nvim",
	"vague2k/vague.nvim",
}
