return {
	{
		"nvim-treesitter/nvim-treesitter",
        enabled = false,
		build = ":TSUpdate",
		config = function()
			require("nvim-treesitter.configs").setup({
				ensure_installed = {
					"bash",
					"c",
					"cmake",
					"cpp",
					"css",
					"csv",
					"diff",
					"dockerfile",
					"git_config",
					"git_rebase",
					"gitattributes",
					"gitcommit",
					"gitignore",
					"go",
					"gomod",
					"gosum",
					"gotmpl",
					"html",
					"java",
					"javascript",
					"jsdoc",
					"json",
					"jsonc",
					"liquid",
					"lua",
					"make",
					"markdown",
					"markdown_inline",
					"nix",
					"proto",
					"python",
					"qmljs",
					"rust",
					"scss",
					"sql",
					"toml",
					"tsx",
					"typst",
					"typescript",
					"vimdoc",
					"vue",
					"yaml",
					"zig",
				},
				sync_install = false,
				auto_install = false,
				highlight = {
					enable = true,
					ignore = { "*.min.js" },
				},
			})
		end,
	},
}
