## Rose Pine theme
# colors:
#   bright:
#     black: "#908caa"
#     red: "#eb6f92"
#     green: "#ABE9B3"
#     yellow: "#f6c177"
#     blue: "#8bbec7"
#     magenta: "#c4a7e7"
#     cyan: "#a3d6df"
#     white: "#e0def4"
#   normal:
#     black: "#16141f"
#     red: "#eb6f92"
#     green: "#ABE9B3"
#     yellow: "#f6c177"
#     blue: "#8bbec7"
#     magenta: "#bb9ede"
#     cyan: "#9ccfd8"
#     white: "#6e6a86"
#   primary:
#     background: "#191724"
#     background2: "#1c1a29"
#     background3: "#1e1c2b"
#     accent: "#ebbcba"
#     foreground: "#e0def4"
#     selection: "#403d52"
#
# font:
#   family: "Roboto"
#   monospace: "Iosevka"
#
# settings:
#   gtk: "rose-pine-gtk"
#   qt_style: "Adwaita-Dark"
#   icon: "icons_papirus"

## Gruvbox theme
# colors:
#   bright:
#     black: "#928374"
#     red: "#fb4934"
#     green: "#b8bb26"
#     yellow: "#fabd2f"
#     blue: "#83a598"
#     magenta: "#d3869b"
#     cyan: "#8ec07c"
#     white: "#ebdbb2"
#   normal:
#     black: "#282828"
#     red: "#cc241d"
#     green: "#98971a"
#     yellow: "#d79921"
#     blue: "#458588"
#     magenta: "#b16286"
#     cyan: "#689d6a"
#     white: "#a89984"
#   primary:
#     background: "#282828"
#     background2: "#3c3836"
#     background3: "#504945"
#     accent: "#fabd2f"
#     foreground: "#ebdbb2"
#     selection: "#504945"
#
# font:
#   family: "Roboto"
#   monospace: "Iosevka"
#
# settings:
#   gtk: "Gruvbox-Dark"
#   qt_style: "Adwaita-Dark"
#   icon: "Gruvbox-Plus-Dark"

## Mellifluous theme  ── generated from ramojus/mellifluous.nvim
# colors:
#   bright:
#     black: "#66665f"
#     red: "#ea8879"
#     green: "#93d29a"
#     yellow: "#e9e199"
#     blue: "#b5a0c9"
#     magenta: "#c99fb7"
#     cyan: "#9dd3c2"
#     white: "#deddd7"
#   normal:
#     black: "#1a1a19"
#     red: "#ea8879"
#     green: "#71c37c"
#     yellow: "#d3cb71"
#     blue: "#9b88b8"
#     magenta: "#b68ba9"
#     cyan: "#7dc2ae"
#     white: "#bcbcb6"
#   primary:
#     background: "#1a1a19"
#     background2: "#222220"
#     background3: "#2b2b28"
#     accent: "#CBAA88"
#     foreground: "#deddd7"
#     selection: "#4a453f"
#     selection_text: "#deddd7"
#     hover: "#383832"
#     border: "#454540"
#
# font:
#   size : 12
#   family: "Inter Display"
#   monospace: "Iosevka"
#
# settings:
#   gtk: "oomox-chezmoi"
#   qt_style: "Adwaita-Dark"
#   icon: "oomox-chezmoi"

# cyberdream
colors:
  normal:
    black: "#16181a"
    red: "#ff6e5e"
    green: "#5eff6c"
    yellow: "#f1ff5e"
    blue: "#5ea1ff"
    magenta: "#ff5ef1"
    cyan: "#5ef1ff"
    white: "#7b8496"

  bright:
    black: "#3c4048"
    red: "#ff6e5e"
    green: "#5eff6c"
    yellow: "#f1ff5e"
    blue: "#5ea1ff"
    magenta: "#ff5ef1"
    cyan: "#5ef1ff"
    white: "#ffffff"

  primary:
    background: "#16181a"
    background2: "#1e2124"
    background3: "#3c4048"
    accent: "#ff5ef1"
    foreground: "#ffffff"
    selection: "#3c4048"
    selection_text: "#ffffff"
    hover: "#1e2124"
    border: "#3c4048"

font:
  size: 12
  family: "Inter Display"
  monospace: "Iosevka"

settings:
  gtk: "oomox-chezmoi"
  qt_style: "Adwaita-Dark"
  icon: "oomox-chezmoi"
